services: 
      db: 
        image: postgres:latest
        ports: 
          - "5433:5432"
        restart: always
        environment: 
          POSTGRES_PASSWORD: changemeinprod!
      
      server: 
        build: . 
        # command: ["npm", "run", "docker:dev"]
        # command: ["npm", "run", "start:prod"]
        command: ["npm", "run", "start:prod"]
        ports: 
          - "3000:3000"
        env_file: 
          .env.docker
        depends_on: 
          - db
        restart: always

